/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as WecomQrCallbackRouteImport } from './routes/wecom-qr-callback'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedBrowseRouteImport } from './routes/_authenticated/browse'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedLabelsRouteImport } from './routes/_authenticated/labels'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedToolsRouteImport } from './routes/_authenticated/tools'
import { Route as AuthenticatedAssetsIndexRouteImport } from './routes/_authenticated/assets/index'
import { Route as AuthenticatedAssetsAgentsRouteImport } from './routes/_authenticated/assets/agents'
import { Route as AuthenticatedAssetsContractsRouteImport } from './routes/_authenticated/assets/contracts'
import { Route as AuthenticatedAssetsFilesRouteImport } from './routes/_authenticated/assets/files'
import { Route as AuthenticatedAssetsHardwareRouteImport } from './routes/_authenticated/assets/hardware'
import { Route as AuthenticatedAssetsInvoicesRouteImport } from './routes/_authenticated/assets/invoices'
import { Route as AuthenticatedAssetsItemsRouteImport } from './routes/_authenticated/assets/items'
import { Route as AuthenticatedAssetsLocationsRouteImport } from './routes/_authenticated/assets/locations'
import { Route as AuthenticatedAssetsRacksRouteImport } from './routes/_authenticated/assets/racks'
import { Route as AuthenticatedAssetsSoftwareRouteImport } from './routes/_authenticated/assets/software'
import { Route as AuthenticatedAssetsUsersRouteImport } from './routes/_authenticated/assets/users'
import { Route as AuthenticatedDictionariesIndexRouteImport } from './routes/_authenticated/dictionaries/index'
import { Route as AuthenticatedDictionariesContracttypesRouteImport } from './routes/_authenticated/dictionaries/contracttypes'
import { Route as AuthenticatedDictionariesDpttypesRouteImport } from './routes/_authenticated/dictionaries/dpttypes'
import { Route as AuthenticatedDictionariesFiletypesRouteImport } from './routes/_authenticated/dictionaries/filetypes'
import { Route as AuthenticatedDictionariesItemtypesRouteImport } from './routes/_authenticated/dictionaries/itemtypes'
import { Route as AuthenticatedDictionariesStatustypesRouteImport } from './routes/_authenticated/dictionaries/statustypes'
import { Route as AuthenticatedDictionariesTagsRouteImport } from './routes/_authenticated/dictionaries/tags'
import { Route as AuthenticatedRackViewIdRouteImport } from './routes/_authenticated/rack-view.$id'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WecomQrCallbackRoute = WecomQrCallbackRouteImport.update({
  id: '/wecom-qr-callback',
  path: '/wecom-qr-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBrowseRoute = AuthenticatedBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLabelsRoute = AuthenticatedLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedToolsRoute = AuthenticatedToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssetsIndexRoute =
  AuthenticatedAssetsIndexRouteImport.update({
    id: '/assets/',
    path: '/assets/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssetsAgentsRoute =
  AuthenticatedAssetsAgentsRouteImport.update({
    id: '/assets/agents',
    path: '/assets/agents',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssetsContractsRoute =
  AuthenticatedAssetsContractsRouteImport.update({
    id: '/assets/contracts',
    path: '/assets/contracts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssetsFilesRoute =
  AuthenticatedAssetsFilesRouteImport.update({
    id: '/assets/files',
    path: '/assets/files',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssetsHardwareRoute =
  AuthenticatedAssetsHardwareRouteImport.update({
    id: '/assets/hardware',
    path: '/assets/hardware',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssetsInvoicesRoute =
  AuthenticatedAssetsInvoicesRouteImport.update({
    id: '/assets/invoices',
    path: '/assets/invoices',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssetsItemsRoute =
  AuthenticatedAssetsItemsRouteImport.update({
    id: '/assets/items',
    path: '/assets/items',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssetsLocationsRoute =
  AuthenticatedAssetsLocationsRouteImport.update({
    id: '/assets/locations',
    path: '/assets/locations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssetsRacksRoute =
  AuthenticatedAssetsRacksRouteImport.update({
    id: '/assets/racks',
    path: '/assets/racks',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssetsSoftwareRoute =
  AuthenticatedAssetsSoftwareRouteImport.update({
    id: '/assets/software',
    path: '/assets/software',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssetsUsersRoute =
  AuthenticatedAssetsUsersRouteImport.update({
    id: '/assets/users',
    path: '/assets/users',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDictionariesIndexRoute =
  AuthenticatedDictionariesIndexRouteImport.update({
    id: '/dictionaries/',
    path: '/dictionaries/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDictionariesContracttypesRoute =
  AuthenticatedDictionariesContracttypesRouteImport.update({
    id: '/dictionaries/contracttypes',
    path: '/dictionaries/contracttypes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDictionariesDpttypesRoute =
  AuthenticatedDictionariesDpttypesRouteImport.update({
    id: '/dictionaries/dpttypes',
    path: '/dictionaries/dpttypes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDictionariesFiletypesRoute =
  AuthenticatedDictionariesFiletypesRouteImport.update({
    id: '/dictionaries/filetypes',
    path: '/dictionaries/filetypes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDictionariesItemtypesRoute =
  AuthenticatedDictionariesItemtypesRouteImport.update({
    id: '/dictionaries/itemtypes',
    path: '/dictionaries/itemtypes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDictionariesStatustypesRoute =
  AuthenticatedDictionariesStatustypesRouteImport.update({
    id: '/dictionaries/statustypes',
    path: '/dictionaries/statustypes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDictionariesTagsRoute =
  AuthenticatedDictionariesTagsRouteImport.update({
    id: '/dictionaries/tags',
    path: '/dictionaries/tags',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRackViewIdRoute = AuthenticatedRackViewIdRouteImport.update({
  id: '/rack-view/$id',
  path: '/rack-view/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/wecom-qr-callback': typeof WecomQrCallbackRoute
  '/browse': typeof AuthenticatedBrowseRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/labels': typeof AuthenticatedLabelsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/assets/agents': typeof AuthenticatedAssetsAgentsRoute
  '/assets/contracts': typeof AuthenticatedAssetsContractsRoute
  '/assets/files': typeof AuthenticatedAssetsFilesRoute
  '/assets/hardware': typeof AuthenticatedAssetsHardwareRoute
  '/assets/invoices': typeof AuthenticatedAssetsInvoicesRoute
  '/assets/items': typeof AuthenticatedAssetsItemsRoute
  '/assets/locations': typeof AuthenticatedAssetsLocationsRoute
  '/assets/racks': typeof AuthenticatedAssetsRacksRoute
  '/assets/software': typeof AuthenticatedAssetsSoftwareRoute
  '/assets/users': typeof AuthenticatedAssetsUsersRoute
  '/dictionaries/contracttypes': typeof AuthenticatedDictionariesContracttypesRoute
  '/dictionaries/dpttypes': typeof AuthenticatedDictionariesDpttypesRoute
  '/dictionaries/filetypes': typeof AuthenticatedDictionariesFiletypesRoute
  '/dictionaries/itemtypes': typeof AuthenticatedDictionariesItemtypesRoute
  '/dictionaries/statustypes': typeof AuthenticatedDictionariesStatustypesRoute
  '/dictionaries/tags': typeof AuthenticatedDictionariesTagsRoute
  '/rack-view/$id': typeof AuthenticatedRackViewIdRoute
  '/assets/': typeof AuthenticatedAssetsIndexRoute
  '/dictionaries/': typeof AuthenticatedDictionariesIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/wecom-qr-callback': typeof WecomQrCallbackRoute
  '/browse': typeof AuthenticatedBrowseRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/labels': typeof AuthenticatedLabelsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/': typeof AuthenticatedIndexRoute
  '/assets/agents': typeof AuthenticatedAssetsAgentsRoute
  '/assets/contracts': typeof AuthenticatedAssetsContractsRoute
  '/assets/files': typeof AuthenticatedAssetsFilesRoute
  '/assets/hardware': typeof AuthenticatedAssetsHardwareRoute
  '/assets/invoices': typeof AuthenticatedAssetsInvoicesRoute
  '/assets/items': typeof AuthenticatedAssetsItemsRoute
  '/assets/locations': typeof AuthenticatedAssetsLocationsRoute
  '/assets/racks': typeof AuthenticatedAssetsRacksRoute
  '/assets/software': typeof AuthenticatedAssetsSoftwareRoute
  '/assets/users': typeof AuthenticatedAssetsUsersRoute
  '/dictionaries/contracttypes': typeof AuthenticatedDictionariesContracttypesRoute
  '/dictionaries/dpttypes': typeof AuthenticatedDictionariesDpttypesRoute
  '/dictionaries/filetypes': typeof AuthenticatedDictionariesFiletypesRoute
  '/dictionaries/itemtypes': typeof AuthenticatedDictionariesItemtypesRoute
  '/dictionaries/statustypes': typeof AuthenticatedDictionariesStatustypesRoute
  '/dictionaries/tags': typeof AuthenticatedDictionariesTagsRoute
  '/rack-view/$id': typeof AuthenticatedRackViewIdRoute
  '/assets': typeof AuthenticatedAssetsIndexRoute
  '/dictionaries': typeof AuthenticatedDictionariesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/wecom-qr-callback': typeof WecomQrCallbackRoute
  '/_authenticated/browse': typeof AuthenticatedBrowseRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/labels': typeof AuthenticatedLabelsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tools': typeof AuthenticatedToolsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/assets/agents': typeof AuthenticatedAssetsAgentsRoute
  '/_authenticated/assets/contracts': typeof AuthenticatedAssetsContractsRoute
  '/_authenticated/assets/files': typeof AuthenticatedAssetsFilesRoute
  '/_authenticated/assets/hardware': typeof AuthenticatedAssetsHardwareRoute
  '/_authenticated/assets/invoices': typeof AuthenticatedAssetsInvoicesRoute
  '/_authenticated/assets/items': typeof AuthenticatedAssetsItemsRoute
  '/_authenticated/assets/locations': typeof AuthenticatedAssetsLocationsRoute
  '/_authenticated/assets/racks': typeof AuthenticatedAssetsRacksRoute
  '/_authenticated/assets/software': typeof AuthenticatedAssetsSoftwareRoute
  '/_authenticated/assets/users': typeof AuthenticatedAssetsUsersRoute
  '/_authenticated/dictionaries/contracttypes': typeof AuthenticatedDictionariesContracttypesRoute
  '/_authenticated/dictionaries/dpttypes': typeof AuthenticatedDictionariesDpttypesRoute
  '/_authenticated/dictionaries/filetypes': typeof AuthenticatedDictionariesFiletypesRoute
  '/_authenticated/dictionaries/itemtypes': typeof AuthenticatedDictionariesItemtypesRoute
  '/_authenticated/dictionaries/statustypes': typeof AuthenticatedDictionariesStatustypesRoute
  '/_authenticated/dictionaries/tags': typeof AuthenticatedDictionariesTagsRoute
  '/_authenticated/rack-view/$id': typeof AuthenticatedRackViewIdRoute
  '/_authenticated/assets/': typeof AuthenticatedAssetsIndexRoute
  '/_authenticated/dictionaries/': typeof AuthenticatedDictionariesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/wecom-qr-callback'
    | '/browse'
    | '/history'
    | '/labels'
    | '/reports'
    | '/settings'
    | '/tools'
    | '/assets/agents'
    | '/assets/contracts'
    | '/assets/files'
    | '/assets/hardware'
    | '/assets/invoices'
    | '/assets/items'
    | '/assets/locations'
    | '/assets/racks'
    | '/assets/software'
    | '/assets/users'
    | '/dictionaries/contracttypes'
    | '/dictionaries/dpttypes'
    | '/dictionaries/filetypes'
    | '/dictionaries/itemtypes'
    | '/dictionaries/statustypes'
    | '/dictionaries/tags'
    | '/rack-view/$id'
    | '/assets/'
    | '/dictionaries/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/wecom-qr-callback'
    | '/browse'
    | '/history'
    | '/labels'
    | '/reports'
    | '/settings'
    | '/tools'
    | '/'
    | '/assets/agents'
    | '/assets/contracts'
    | '/assets/files'
    | '/assets/hardware'
    | '/assets/invoices'
    | '/assets/items'
    | '/assets/locations'
    | '/assets/racks'
    | '/assets/software'
    | '/assets/users'
    | '/dictionaries/contracttypes'
    | '/dictionaries/dpttypes'
    | '/dictionaries/filetypes'
    | '/dictionaries/itemtypes'
    | '/dictionaries/statustypes'
    | '/dictionaries/tags'
    | '/rack-view/$id'
    | '/assets'
    | '/dictionaries'
  id:
    | '__root__'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/wecom-qr-callback'
    | '/_authenticated/browse'
    | '/_authenticated/history'
    | '/_authenticated/labels'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/tools'
    | '/_authenticated/'
    | '/_authenticated/assets/agents'
    | '/_authenticated/assets/contracts'
    | '/_authenticated/assets/files'
    | '/_authenticated/assets/hardware'
    | '/_authenticated/assets/invoices'
    | '/_authenticated/assets/items'
    | '/_authenticated/assets/locations'
    | '/_authenticated/assets/racks'
    | '/_authenticated/assets/software'
    | '/_authenticated/assets/users'
    | '/_authenticated/dictionaries/contracttypes'
    | '/_authenticated/dictionaries/dpttypes'
    | '/_authenticated/dictionaries/filetypes'
    | '/_authenticated/dictionaries/itemtypes'
    | '/_authenticated/dictionaries/statustypes'
    | '/_authenticated/dictionaries/tags'
    | '/_authenticated/rack-view/$id'
    | '/_authenticated/assets/'
    | '/_authenticated/dictionaries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  WecomQrCallbackRoute: typeof WecomQrCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wecom-qr-callback': {
      id: '/wecom-qr-callback'
      path: '/wecom-qr-callback'
      fullPath: '/wecom-qr-callback'
      preLoaderRoute: typeof WecomQrCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/browse': {
      id: '/_authenticated/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof AuthenticatedBrowseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/labels': {
      id: '/_authenticated/labels'
      path: '/labels'
      fullPath: '/labels'
      preLoaderRoute: typeof AuthenticatedLabelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tools': {
      id: '/_authenticated/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthenticatedToolsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assets/': {
      id: '/_authenticated/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AuthenticatedAssetsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assets/agents': {
      id: '/_authenticated/assets/agents'
      path: '/assets/agents'
      fullPath: '/assets/agents'
      preLoaderRoute: typeof AuthenticatedAssetsAgentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assets/contracts': {
      id: '/_authenticated/assets/contracts'
      path: '/assets/contracts'
      fullPath: '/assets/contracts'
      preLoaderRoute: typeof AuthenticatedAssetsContractsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assets/files': {
      id: '/_authenticated/assets/files'
      path: '/assets/files'
      fullPath: '/assets/files'
      preLoaderRoute: typeof AuthenticatedAssetsFilesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assets/hardware': {
      id: '/_authenticated/assets/hardware'
      path: '/assets/hardware'
      fullPath: '/assets/hardware'
      preLoaderRoute: typeof AuthenticatedAssetsHardwareRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assets/invoices': {
      id: '/_authenticated/assets/invoices'
      path: '/assets/invoices'
      fullPath: '/assets/invoices'
      preLoaderRoute: typeof AuthenticatedAssetsInvoicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assets/items': {
      id: '/_authenticated/assets/items'
      path: '/assets/items'
      fullPath: '/assets/items'
      preLoaderRoute: typeof AuthenticatedAssetsItemsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assets/locations': {
      id: '/_authenticated/assets/locations'
      path: '/assets/locations'
      fullPath: '/assets/locations'
      preLoaderRoute: typeof AuthenticatedAssetsLocationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assets/racks': {
      id: '/_authenticated/assets/racks'
      path: '/assets/racks'
      fullPath: '/assets/racks'
      preLoaderRoute: typeof AuthenticatedAssetsRacksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assets/software': {
      id: '/_authenticated/assets/software'
      path: '/assets/software'
      fullPath: '/assets/software'
      preLoaderRoute: typeof AuthenticatedAssetsSoftwareRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assets/users': {
      id: '/_authenticated/assets/users'
      path: '/assets/users'
      fullPath: '/assets/users'
      preLoaderRoute: typeof AuthenticatedAssetsUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dictionaries/': {
      id: '/_authenticated/dictionaries/'
      path: '/dictionaries'
      fullPath: '/dictionaries/'
      preLoaderRoute: typeof AuthenticatedDictionariesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dictionaries/contracttypes': {
      id: '/_authenticated/dictionaries/contracttypes'
      path: '/dictionaries/contracttypes'
      fullPath: '/dictionaries/contracttypes'
      preLoaderRoute: typeof AuthenticatedDictionariesContracttypesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dictionaries/dpttypes': {
      id: '/_authenticated/dictionaries/dpttypes'
      path: '/dictionaries/dpttypes'
      fullPath: '/dictionaries/dpttypes'
      preLoaderRoute: typeof AuthenticatedDictionariesDpttypesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dictionaries/filetypes': {
      id: '/_authenticated/dictionaries/filetypes'
      path: '/dictionaries/filetypes'
      fullPath: '/dictionaries/filetypes'
      preLoaderRoute: typeof AuthenticatedDictionariesFiletypesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dictionaries/itemtypes': {
      id: '/_authenticated/dictionaries/itemtypes'
      path: '/dictionaries/itemtypes'
      fullPath: '/dictionaries/itemtypes'
      preLoaderRoute: typeof AuthenticatedDictionariesItemtypesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dictionaries/statustypes': {
      id: '/_authenticated/dictionaries/statustypes'
      path: '/dictionaries/statustypes'
      fullPath: '/dictionaries/statustypes'
      preLoaderRoute: typeof AuthenticatedDictionariesStatustypesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dictionaries/tags': {
      id: '/_authenticated/dictionaries/tags'
      path: '/dictionaries/tags'
      fullPath: '/dictionaries/tags'
      preLoaderRoute: typeof AuthenticatedDictionariesTagsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rack-view/$id': {
      id: '/_authenticated/rack-view/$id'
      path: '/rack-view/$id'
      fullPath: '/rack-view/$id'
      preLoaderRoute: typeof AuthenticatedRackViewIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBrowseRoute: typeof AuthenticatedBrowseRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedLabelsRoute: typeof AuthenticatedLabelsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedToolsRoute: typeof AuthenticatedToolsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAssetsAgentsRoute: typeof AuthenticatedAssetsAgentsRoute
  AuthenticatedAssetsContractsRoute: typeof AuthenticatedAssetsContractsRoute
  AuthenticatedAssetsFilesRoute: typeof AuthenticatedAssetsFilesRoute
  AuthenticatedAssetsHardwareRoute: typeof AuthenticatedAssetsHardwareRoute
  AuthenticatedAssetsInvoicesRoute: typeof AuthenticatedAssetsInvoicesRoute
  AuthenticatedAssetsItemsRoute: typeof AuthenticatedAssetsItemsRoute
  AuthenticatedAssetsLocationsRoute: typeof AuthenticatedAssetsLocationsRoute
  AuthenticatedAssetsRacksRoute: typeof AuthenticatedAssetsRacksRoute
  AuthenticatedAssetsSoftwareRoute: typeof AuthenticatedAssetsSoftwareRoute
  AuthenticatedAssetsUsersRoute: typeof AuthenticatedAssetsUsersRoute
  AuthenticatedDictionariesContracttypesRoute: typeof AuthenticatedDictionariesContracttypesRoute
  AuthenticatedDictionariesDpttypesRoute: typeof AuthenticatedDictionariesDpttypesRoute
  AuthenticatedDictionariesFiletypesRoute: typeof AuthenticatedDictionariesFiletypesRoute
  AuthenticatedDictionariesItemtypesRoute: typeof AuthenticatedDictionariesItemtypesRoute
  AuthenticatedDictionariesStatustypesRoute: typeof AuthenticatedDictionariesStatustypesRoute
  AuthenticatedDictionariesTagsRoute: typeof AuthenticatedDictionariesTagsRoute
  AuthenticatedRackViewIdRoute: typeof AuthenticatedRackViewIdRoute
  AuthenticatedAssetsIndexRoute: typeof AuthenticatedAssetsIndexRoute
  AuthenticatedDictionariesIndexRoute: typeof AuthenticatedDictionariesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBrowseRoute: AuthenticatedBrowseRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedLabelsRoute: AuthenticatedLabelsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedToolsRoute: AuthenticatedToolsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAssetsAgentsRoute: AuthenticatedAssetsAgentsRoute,
  AuthenticatedAssetsContractsRoute: AuthenticatedAssetsContractsRoute,
  AuthenticatedAssetsFilesRoute: AuthenticatedAssetsFilesRoute,
  AuthenticatedAssetsHardwareRoute: AuthenticatedAssetsHardwareRoute,
  AuthenticatedAssetsInvoicesRoute: AuthenticatedAssetsInvoicesRoute,
  AuthenticatedAssetsItemsRoute: AuthenticatedAssetsItemsRoute,
  AuthenticatedAssetsLocationsRoute: AuthenticatedAssetsLocationsRoute,
  AuthenticatedAssetsRacksRoute: AuthenticatedAssetsRacksRoute,
  AuthenticatedAssetsSoftwareRoute: AuthenticatedAssetsSoftwareRoute,
  AuthenticatedAssetsUsersRoute: AuthenticatedAssetsUsersRoute,
  AuthenticatedDictionariesContracttypesRoute:
    AuthenticatedDictionariesContracttypesRoute,
  AuthenticatedDictionariesDpttypesRoute:
    AuthenticatedDictionariesDpttypesRoute,
  AuthenticatedDictionariesFiletypesRoute:
    AuthenticatedDictionariesFiletypesRoute,
  AuthenticatedDictionariesItemtypesRoute:
    AuthenticatedDictionariesItemtypesRoute,
  AuthenticatedDictionariesStatustypesRoute:
    AuthenticatedDictionariesStatustypesRoute,
  AuthenticatedDictionariesTagsRoute: AuthenticatedDictionariesTagsRoute,
  AuthenticatedRackViewIdRoute: AuthenticatedRackViewIdRoute,
  AuthenticatedAssetsIndexRoute: AuthenticatedAssetsIndexRoute,
  AuthenticatedDictionariesIndexRoute: AuthenticatedDictionariesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  WecomQrCallbackRoute: WecomQrCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
